/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo.projectuas;

/**
 *
 * @author Birawa Kaca Buana Gora
 */
public class kasirMakanan extends javax.swing.JFrame {

    String pilihan = "";
    int hrg_makanan, jml_beli, total, bayar, kembalian;
    
    /**
     * Creates new form kasirMakanan
     */
    public kasirMakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnHitungHrg = new javax.swing.JButton();
        btnTotalKmbli = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CB_PilihMenu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        teks_HrgMkn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teks_JmlBeli = new javax.swing.JTextField();
        teks_TotalHrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        teks_TotalByr = new javax.swing.JTextField();
        teks_TotalKmbli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        btnReset.setBackground(new java.awt.Color(204, 102, 0));
        btnReset.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setBorderPainted(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);
        btnReset.setBounds(380, 390, 121, 29);

        btnHitungHrg.setBackground(new java.awt.Color(204, 102, 0));
        btnHitungHrg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnHitungHrg.setForeground(new java.awt.Color(255, 255, 255));
        btnHitungHrg.setText("Hitung Harga");
        btnHitungHrg.setBorderPainted(false);
        btnHitungHrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungHrgActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitungHrg);
        btnHitungHrg.setBounds(380, 200, 121, 25);

        btnTotalKmbli.setBackground(new java.awt.Color(204, 102, 0));
        btnTotalKmbli.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnTotalKmbli.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalKmbli.setText("Kembalian");
        btnTotalKmbli.setBorderPainted(false);
        btnTotalKmbli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalKmbliActionPerformed(evt);
            }
        });
        jPanel1.add(btnTotalKmbli);
        btnTotalKmbli.setBounds(380, 350, 120, 25);

        jLabel12.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 0, 500, 17);

        jLabel13.setFont(new java.awt.Font("Dopestyle ", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Resto Kuno-Kini");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 20, 520, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Makanan");

        CB_PilihMenu.setEditable(true);
        CB_PilihMenu.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        CB_PilihMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Menu", "Special Fried Rice", "Fire Spageti", "Burger Deluxe", "Coffee Latte", "Milk Shake" }));
        CB_PilihMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_PilihMenuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rp.");

        teks_HrgMkn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Makanan");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Beli");

        teks_JmlBeli.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        teks_JmlBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_JmlBeliActionPerformed(evt);
            }
        });

        teks_TotalHrg.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        teks_TotalHrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_TotalHrgActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rp.");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Harga");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(CB_PilihMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jLabel10)
                            .addGap(1, 1, 1)
                            .addComponent(teks_HrgMkn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(teks_JmlBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jLabel8)
                            .addGap(1, 1, 1)
                            .addComponent(teks_TotalHrg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(CB_PilihMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel10)
                        .addComponent(teks_HrgMkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(teks_JmlBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)
                        .addComponent(teks_TotalHrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 110, 360, 170);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Bayar");

        teks_TotalByr.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        teks_TotalByr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_TotalByrActionPerformed(evt);
            }
        });

        teks_TotalKmbli.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        teks_TotalKmbli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks_TotalKmbliActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rp.");

        jLabel14.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Kembalian");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(teks_TotalByr, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jLabel11)
                            .addGap(1, 1, 1)
                            .addComponent(teks_TotalKmbli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(teks_TotalByr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel11)
                        .addComponent(teks_TotalKmbli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 300, 360, 90);

        jLabel15.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 440, 500, 17);

        jLabel9.setFont(new java.awt.Font("Just Another Courier", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Makan enak jangan sendirian...");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 420, 310, 30);

        jLabel16.setFont(new java.awt.Font("Vintage Decorative signs", 0, 150)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 102, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("h");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(320, -90, 270, 220);

        jLabel17.setFont(new java.awt.Font("Vintage Decorative signs", 0, 150)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 102, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("q");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(-50, -20, 270, 160);

        jLabel7.setFont(new java.awt.Font("Kamera Dings", 0, 100)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("a");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 80, 140, 120);

        jLabel18.setFont(new java.awt.Font("Vintage Decorative signs", 0, 150)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 102, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("z");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(130, 240, 270, 190);

        jLabel19.setFont(new java.awt.Font("Fireworks", 0, 150)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("z");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(360, 240, 160, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teks_TotalHrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_TotalHrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_TotalHrgActionPerformed

    private void teks_JmlBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_JmlBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_JmlBeliActionPerformed

    private void teks_TotalByrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_TotalByrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_TotalByrActionPerformed

    private void teks_TotalKmbliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks_TotalKmbliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks_TotalKmbliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        CB_PilihMenu.setSelectedIndex(0);
        teks_HrgMkn.setText("");
        teks_JmlBeli.setText("");
        teks_TotalHrg.setText("");
        teks_TotalByr.setText("");
        teks_TotalKmbli.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungHrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungHrgActionPerformed
        // TODO add your handling code here:
        hrg_makanan = Integer.parseInt(teks_HrgMkn.getText());
        jml_beli = Integer.parseInt(teks_JmlBeli.getText());
        
        total = hrg_makanan * jml_beli;
        
        teks_TotalHrg.setText("" + Integer.toString(total));
    }//GEN-LAST:event_btnHitungHrgActionPerformed

    private void CB_PilihMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_PilihMenuActionPerformed
        // TODO add your handling code here:
        pilihan = (String) CB_PilihMenu.getSelectedItem();
        switch (pilihan) {
            case "Special Fried Rice":
                hrg_makanan = 20000;
                break;
            case "Fire Spageti":
                hrg_makanan = 30000;
                break;
            case "Burger Deluxe":
                hrg_makanan = 25000;
                break;
            case "Coffee Latte":
                hrg_makanan = 10000;
                break;
            case "Milk Shake":
                hrg_makanan = 5000;
                break;
        }
        teks_HrgMkn.setText("" + Integer.toString (hrg_makanan));
    }//GEN-LAST:event_CB_PilihMenuActionPerformed

    private void btnTotalKmbliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalKmbliActionPerformed
        // TODO add your handling code here:
        bayar = Integer.parseInt(teks_TotalByr.getText());
        kembalian = bayar - total;
        
        teks_TotalKmbli.setText("" + Integer.toString(kembalian));
    }//GEN-LAST:event_btnTotalKmbliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasirMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasirMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasirMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasirMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasirMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_PilihMenu;
    private javax.swing.JButton btnHitungHrg;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalKmbli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField teks_HrgMkn;
    private javax.swing.JTextField teks_JmlBeli;
    private javax.swing.JTextField teks_TotalByr;
    private javax.swing.JTextField teks_TotalHrg;
    private javax.swing.JTextField teks_TotalKmbli;
    // End of variables declaration//GEN-END:variables
}
